### ISSUE TITLE
Old ipaddress shown in integration overview

### ISSUE THREAD

**Issue by Bram-diederik** [amosyuen/ha-tplink-deco#105]
Minor issue.

I gave my main deco a fixed ipaddess and the old ipadres is still shown on the deco panel at the integration overview.

See printscreens.
![Screenshot_20220923-181836_Home Assistant](https://user-images.githubusercontent.com/53519837/192007659-c3dccb7e-e6cc-4a99-90a3-c50b0c9ad6d2.jpg)
![Screenshot_20220923-181827_Home Assistant](https://user-images.githubusercontent.com/53519837/192007705-39f0bfb8-2479-4372-b000-63d2143769ee.jpg)

**Comment by richardwonka** [comment]
+1 affected

**Comment by richardwonka** [comment]
> +1 affected, but not minor, since this happens, the integration fails

When I enter the IP address and access data that worked so far, the integration says:

`Retrying setup: Cannot connect to host none:80 ssl:default [Name does not resolve] `

**Comment by amosyuen** [comment]
Please see if https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.2.3 helps with this issue

**Comment by richardwonka** [comment]
Just re-added the Integration and it’s looking good.

**Comment by richardwonka** [comment]
Integration is failing again. Showing the old default IP address, it appears the fix was short-lived.

**Comment by grigorye** [comment]
I'm not sure what if it's the same issue, but in my case the integration was working for a month or so, but today I discovered that it's broken since the IP address was reset to 192.168.0.1. When I "reconfigure" and enter the correct address/password, it says that it succeeded, however nothing changes on the devices page - it still shows the error and if I "reconfigure" again, it still shows "192.168.0.1" as the IP address/no password and etc.

<img width="278" alt="Screenshot 2022-12-27 at 15 59 50" src="https://user-images.githubusercontent.com/803905/209684467-4090110b-0e22-4e71-ab26-7993fa4ce13e.png">

**Comment by amosyuen** [comment]
I made some changes in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.2.5 that should update the title properly. I'm not entirely sure why the config gets messed up, but I added an extra defensive check. Please try updating and you might need to remove then re-add the integration.

**Comment by Waterchasd** [comment]
> 

I was having the same error as grigorye was having. After I removed and reinstalled the integration, all is working now. Big thanks for the excellent work.
